export const productList = [
  {
    id: 1,
    title: "96 Nuptse Dip Dye Korea Puffers Jacket",
    price: 400.0,
    img: "/images/products/96-nuptse-jacket.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 20,
  },
  {
    id: 2,
    title: "Paradigm Chilliwack Black Label Jacket",
    price: 349.99,
    img: "/images/products/chilliwack-black-jacket.png",
    stars: 4.5,
    tag: "NEW",
    sale: false,
    saleValue: 30,
  },
  {
    id: 3,
    title: "Freestyle Crew Racer leather jacket",
    price: 1000.0,
    img: "/images/products/paul-puffer-bomber-jacket.png",
    stars: 5,
    tag: "HOT",
    sale: true,
    saleValue: 50,
  },
  {
    id: 4,
    title: "1996 Retro Nuptse Cashmere Jacket in Gray",
    price: 149.99,
    img: "/images/products/1996-retro-nuptse-jacket.png",
    stars: 5,
    tag: "NEW" && "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 5,
    title: "Paul Quilted Nylon Puffer bomber jacket",
    price: 300.0,
    img: "/images/products/paul-puffer-bomber-jacket.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 10,
  },
  {
    id: 6,
    title: "Chilliwack jacket Bomber HUMANATURE",
    price: 1195.0,
    img: "/images/products/chilliwack-jacket-Bomber-HUMANATURE.png",
    stars: 5,
    tag: "NEW",
    sale: false,
    saleValue: 0,
  },
  {
    id: 7,
    title: "Chilliwack black Bomber HUMANATURE",
    price: 1195.0,
    img: "/images/products/chilliwack-black-jacket.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 8,
    title: "96 Nuptse Dip Dye bomber Jacket",
    price: 400.99,
    img: "/images/products/96-bomber-jacket.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 9,
    title: "Oversized real leather harrington jacket in black",
    price: 249.99,
    img: "/images/products/oversized-leather-jacket-black.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 10,
    title: "Men's Diamond Quilted Bomber Hoody",
    price: 199.95,
    img: "/images/products/bomber-hoody.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 11,
    title: "Paradigm Chilliwack coat Black Label",
    price: 1495.0,
    img: "/images/products/chilliwack-coat-black.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
  {
    id: 12,
    title: "Men's Torrentshell 3L Rain Jacket in Brown",
    price: 149.0,
    img: "/images/products/torrentshell-rain-jacket-brown.png",
    stars: 5,
    tag: "HOT",
    sale: false,
    saleValue: 0,
  },
];

export const usersList = [
  {
    id: "0001",
    name: "Henrique William Oliveira da Silva",
    username: "sucodeuvahj",
    password: "Teste@123",
    email: "os.heriquewilliam@gmail.com",
    lists: [{ productWish: ["12", "4"] }, { productBag: ["10", "8"] }],
  },
];
